packages:
  - "packages/*"

catalog:
  react: "*"
  react-dom: "*"
  typescript: "*"
  phaser: "*"
  "@types/react": "*"
  "@types/react-dom": "*"
  "@types/node": "*"
  "@dnd-kit/core": "*"
  "@dnd-kit/utilities": "*"
  "@colyseus/schema": "*"
  colyseus: "*"
  express: "*"
  vite: "*"
  nodemon: "*"
  ts-node: "*"
  "matter-js": "*"
  "@types/matter-js": "*"
