packages:
  - packages/*
catalog:
  "@types/express": ^4.17.21
  "@types/matter-js": ^0.19.8
  "@types/node": ^22.15.2
  "@vitejs/plugin-react": ^4.3.1
  colyseus.js: ^0.16.0
  dotenv: ^16.4.5
  express: ^4.19.2
  matter-js: ^0.20.0
  phaser: ^3.88.2
  simplex-noise: ^4.0.3
  tsx: ^4.16.2
  typescript: ^5.8.3
  vite: ^6.3.1
  "@colyseus/schema": "^3.0.0"
  colyseus: "^0.16.0"
  "@colyseus/auth": "^0.16.0"
  "@colyseus/core": "^0.16.0"
  "@colyseus/loadtest": "^0.16.0"
  "@colyseus/monitor": "^0.16.0"
  "@colyseus/playground": "^0.16.0"
  "@colyseus/testing": "^0.16.0"
  "@colyseus/tools": "^0.16.0"
  "@colyseus/uwebsockets-transport": "^0.16.0"
