packages:
  - "packages/*"

catalog:
  react: "*"
  react-dom: "*"
  typescript: "*"
  phaser: "*"
  "@types/react": "*"
  "@types/react-dom": "*"
  "@types/node": "*"
  "@colyseus/schema": "*"
  colyseus: "*"
  express: "*"
  vite: "*"
  nodemon: "*"
  ts-node: "*"
  "matter-js": "*"
  "@types/matter-js": "*"
  "react-rnd": "*"
  vitest: "3.1.3"
  "@vitest/ui": "3.1.3"
  "@vitest/coverage-v8": "3.1.3"
  "@testing-library/react": "*"
  "@testing-library/jest-dom": "*"
  "@testing-library/user-event": "*"
  "jsdom": "*"
  eslint: "*"
  "@eslint/js": "*"
  "typescript-eslint": "*"
  globals: "*"
