packages:
  - "packages/*"

catalog:
  "colyseus.js": "*"
  "phaser": "*"
  "typescript": "^4.6.3"
  "@colyseus/core": "*"
  "@colyseus/monitor": "*"
  "@colyseus/schema": "*"
  "@colyseus/playground": "*"
  "@colyseus/tools": "*"
  "colyseus": "*"
  "@colyseus/loadtest": "*"
  "@colyseus/testing": "*"
  "tsx": "*"
