import { expect } from "chai";
import "mocha";
import Matter, { Vector } from "matter-js";
import { IScenario, ISerializedPhysicsEngineState } from "./types";
import { PhysicsEngine } from "../PhysicsEngine";
import { eccentricOrbitScenario } from "./eccentric-orbit.scenario";
import { runScenario, runTestAndSnapshot } from "./test-runner.helper";

describe("PhysicsEngine Celestial Mechanics: Eccentric Orbit", () => {
  // Removed skipped explicit assertion test block (lines 10-109)
  // in favor of the 1-tick snapshot test generated by snapshotSteps.

  // Dynamically generate snapshot tests
  if (eccentricOrbitScenario.snapshotSteps) {
    eccentricOrbitScenario.snapshotSteps.forEach((steps) => {
      it(`should match snapshot after ${steps} steps of eccentric orbit`, () => {
        runTestAndSnapshot(
          eccentricOrbitScenario,
          eccentricOrbitScenario.id, // Use scenario ID as base name
          steps
        );
      });
    });
  }
});
